-- MySQL Script generated by MySQL Workbench
-- Tue Aug  5 22:04:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(100) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `seasonality` VARCHAR(20) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stores` (
  `storeID` INT NOT NULL,
  `region` VARCHAR(50) NULL,
  `store _name` VARCHAR(100) NULL,
  PRIMARY KEY (`storeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventory_log` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventory_log` (
  `inventoryID` INT NOT NULL,
  `productID` INT NULL,
  `storeID` INT NULL,
  `date` DATE NULL,
  `inventory_level` INT NULL,
  `units_ordered` INT NULL,
  `demand_foreast` DOUBLE NULL,
  PRIMARY KEY (`inventoryID`),
  CONSTRAINT `productID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`products` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `storeID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`stores` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sales` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sales` (
  `saleID` INT NOT NULL,
  `productID` INT NULL,
  `storeID` INT NULL,
  `date` DATE NULL,
  `units_sold` INT NULL,
  `discount` FLOAT NULL,
  `holiday_promo` TINYINT NULL,
  PRIMARY KEY (`saleID`),
  UNIQUE INDEX `saleID_UNIQUE` (`saleID` ASC) VISIBLE,
  CONSTRAINT `productID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`products` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `storeID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`stores` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`external factors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`external factors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`external factors` (
  `factorID` INT NOT NULL,
  `date` DATE NULL,
  `storeID` INT NULL,
  `weather_condition` VARCHAR(50) NULL,
  `competitor_pricing` DOUBLE NULL,
  PRIMARY KEY (`factorID`),
  UNIQUE INDEX `factorID_UNIQUE` (`factorID` ASC) VISIBLE,
  CONSTRAINT `storeID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`stores` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
